# shellcheck shell=bash
# Shared helpers for macos-bootstrap. Sourced, not executed.

if [ -n "${MACOS_BOOTSTRAP_COMMON_LOADED:-}" ]; then
  return 0 2>/dev/null || exit 0
fi
MACOS_BOOTSTRAP_COMMON_LOADED=1

DRY_RUN="${DRY_RUN:-false}"
ASSUME_YES="${ASSUME_YES:-false}"

# --- colors ---------------------------------------------------------------

_c_blue=""
_c_green=""
_c_yellow=""
_c_red=""
_c_dim=""
_c_bold=""
_c_reset=""

if [ -t 1 ] && command -v tput >/dev/null 2>&1; then
  _ncolors="$(tput colors 2>/dev/null || echo 0)"
  if [ "${_ncolors:-0}" -ge 8 ]; then
    _c_blue="$(tput setaf 4)"
    _c_green="$(tput setaf 2)"
    _c_yellow="$(tput setaf 3)"
    _c_red="$(tput setaf 1)"
    _c_dim="$(tput dim)"
    _c_bold="$(tput bold)"
    _c_reset="$(tput sgr0)"
  fi
fi

log_step()    { printf '\n%s==>%s %s%s%s\n'  "$_c_blue" "$_c_reset" "$_c_bold" "$*" "$_c_reset"; }
log_info()    { printf '    %s\n' "$*"; }
log_success() { printf '    %s✓%s %s\n' "$_c_green" "$_c_reset" "$*"; }
log_warn()    { printf '    %s!%s %s\n' "$_c_yellow" "$_c_reset" "$*" >&2; }
log_error()   { printf '    %s✗%s %s\n' "$_c_red" "$_c_reset" "$*" >&2; }
log_dim()     { printf '    %s%s%s\n' "$_c_dim" "$*" "$_c_reset"; }

die() {
  log_error "$*"
  exit 1
}

# --- predicates -----------------------------------------------------------

is_macos() {
  [ "$(uname -s)" = "Darwin" ]
}

is_apple_silicon() {
  [ "$(uname -m)" = "arm64" ]
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

is_truthy() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|y|on) return 0 ;;
    *) return 1 ;;
  esac
}

is_falsy() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    0|false|no|n|off) return 0 ;;
    *) return 1 ;;
  esac
}

is_dry_run() {
  is_truthy "$DRY_RUN"
}

# --- config ---------------------------------------------------------------

macos_bootstrap_load_config() {
  local defaults="$MACOS_BOOTSTRAP_ROOT/config/config.defaults.sh"
  local example="$MACOS_BOOTSTRAP_ROOT/config/config.example.sh"
  local local_cfg="$MACOS_BOOTSTRAP_ROOT/config/config.sh"

  if [ -f "$defaults" ]; then
    # shellcheck source=/dev/null
    source "$defaults"
  else
    log_warn "No config/config.defaults.sh"
  fi

  if [ ! -f "$local_cfg" ] && [ -f "$example" ]; then
    cp "$example" "$local_cfg"
    log_info "Wrote $local_cfg from the example (edit USER_NAME, USER_EMAIL, and options)."
  fi

  if [ -f "$local_cfg" ]; then
    # shellcheck source=/dev/null
    source "$local_cfg"
  fi

  # Derived — not layer keys. Empty git/browser identity follows USER_*.
  if [ -z "${GIT_USER_NAME:-}" ]; then
    GIT_USER_NAME="${USER_NAME:-}"
  fi
  if [ -z "${GIT_USER_EMAIL:-}" ]; then
    GIT_USER_EMAIL="${USER_EMAIL:-}"
  fi
  if [ -z "${CHROME_GOOGLE_ACCOUNT:-}" ]; then
    CHROME_GOOGLE_ACCOUNT="${USER_EMAIL:-}"
  fi
  if [ -z "${FIREFOX_SYNC_ACCOUNT:-}" ]; then
    FIREFOX_SYNC_ACCOUNT="${USER_EMAIL:-}"
  fi
  if [ -z "${SSH_KEY_COMMENT:-}" ]; then
    SSH_KEY_COMMENT="${GIT_USER_EMAIL:-}"
  fi

  macos_bootstrap_write_effective_config
  # shellcheck source=/dev/null
  source "$MACOS_BOOTSTRAP_ROOT/config/effective.config"
}

# Names assigned by config.defaults.sh (clean bash, before vs after source).
macos_bootstrap_default_config_keys() {
  local defaults="$MACOS_BOOTSTRAP_ROOT/config/config.defaults.sh"
  [ -f "$defaults" ] || return 0
  env -i PATH="$PATH" bash --noprofile --norc -c '
    before="$(compgen -A variable | sort)"
    # shellcheck source=/dev/null
    source "$1"
    after="$(compgen -A variable | sort)"
    comm -13 <(printf "%s\n" "$before") <(printf "%s\n" "$after")
  ' _ "$defaults"
}

# Snapshot the merged config, then load_config sources it as the runtime config.
macos_bootstrap_write_effective_config() {
  local dest="$MACOS_BOOTSTRAP_ROOT/config/effective.config"
  local var

  {
    printf '%s\n' "# Generated by macos_bootstrap_load_config. Do not edit."
    printf '%s\n' "# Layers: config.defaults.sh, then config.sh if present."
    printf '%s\n' "# Sourced after write — this is the config the run uses."
    printf '\n'
    while IFS= read -r var; do
      [ -n "$var" ] || continue
      if declare -p "$var" >/dev/null 2>&1; then
        # -g so sourcing this file from a function still sets globals.
        declare -p "$var" | sed -E 's/^declare -a /declare -ga /; s/^declare -- /declare -g /; s/^declare -x /declare -gx /'
      fi
    done < <(macos_bootstrap_default_config_keys)
  } > "$dest"
}

# --- run wrappers ---------------------------------------------------------

# Run a command, or print it during --dry-run.
run() {
  if is_dry_run; then
    log_dim "[dry-run] $*"
    return 0
  fi
  "$@"
}

# Like run, but swallow a non-zero exit and warn instead of aborting.
run_ok() {
  if is_dry_run; then
    log_dim "[dry-run] $*"
    return 0
  fi
  if ! "$@"; then
    log_warn "Command failed (continuing): $*"
    return 0
  fi
}

confirm() {
  local prompt="${1:-Continue?}"
  local reply

  if is_truthy "$ASSUME_YES"; then
    return 0
  fi
  if [ ! -t 0 ]; then
    die "Not a tty. Re-run with --yes to skip confirmation."
  fi

  printf '%s [%s/%s] ' "$prompt" "y" "N"
  read -r reply
  case "$(printf '%s' "$reply" | tr '[:upper:]' '[:lower:]')" in
    y|yes) return 0 ;;
    *) return 1 ;;
  esac
}

require_macos() {
  if is_macos; then
    return 0
  fi
  die "This bootstrap is for macOS. Found $(uname -s)."
}

# sudo(8) sets euid to 0. That is not a root login; SUDO_USER is the real account.
running_via_sudo() {
  [ "$(id -u)" -eq 0 ] && [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]
}

macos_bootstrap_login_user() {
  if running_via_sudo; then
    printf '%s' "$SUDO_USER"
  else
    id -un
  fi
}

# Spaces (and other whitespace) to hyphens; squeeze and trim hyphens. Keep case.
macos_spaces_to_hyphens() {
  printf '%s' "${1:-}" | tr -s '[:space:]' '-' | sed -E 's/-+/-/g; s/^-//; s/-$//'
}

# Bonjour LocalHostName: lowercase [a-z0-9-].
macos_bonjour_slug() {
  printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed -E 's/-+/-/g; s/^-//; s/-$//'
}

# About This Mac string → no "inch", no parens/commas, no spaces.
macos_normalize_marketing() {
  local s="${1:-}"
  s="$(printf '%s' "$s" | sed -E 's/([0-9]+)-[Ii]nch/\1in/g; s/([0-9]+) [Ii]nch/\1in/g')"
  s="$(printf '%s' "$s" | tr -d '(),')"
  macos_spaces_to_hyphens "$s"
}

macos_hardware_serial() {
  local s=""
  if command_exists ioreg; then
    s="$(ioreg -c IOPlatformExpertDevice -d 2 2>/dev/null | awk -F'"' '/IOPlatformSerialNumber/{print $4; exit}')"
  fi
  if [ -z "$s" ] && command_exists system_profiler; then
    s="$(system_profiler SPHardwareDataType 2>/dev/null | awk -F': ' '/Serial Number/{print $2; exit}' | tr -d '[:space:]')"
  fi
  printf '%s' "$s"
}

macos_hardware_model_name() {
  command_exists system_profiler || return 1
  system_profiler SPHardwareDataType 2>/dev/null | awk -F': ' '/^ *Model Name:/{print $2; exit}'
}

macos_hardware_model_identifier() {
  command_exists system_profiler || return 1
  system_profiler SPHardwareDataType 2>/dev/null | awk -F': ' '/^ *Model Identifier:/{print $2; exit}'
}

# Firmware marketing name from ioreg, e.g. MacBook Pro (16-inch, 2021).
# Same dump as https://www.macosadventures.com/2024/07/16/how-to-get-macbook-display-size-via-script/
macos_ioreg_product_name() {
  local name=""
  command_exists ioreg || return 1
  name="$(
    ioreg -l 2>/dev/null | awk -F'"' '
      /product-name/ {
        if ($4 ~ /[0-9]+-inch/) { print $4; found=1; exit }
        if (!backup && $4 ~ /Mac/) backup = $4
      }
      END { if (!found && backup != "") print backup }
    '
  )"
  name="$(printf '%s' "$name" | sed -E 's/^[[:space:]]+//;s/[[:space:]]+$//')"
  [ -n "$name" ] || return 1
  printf '%s' "$name"
}

# Early M-series Airs omit inches in product-name; they are all 13-inch.
macos_early_m_air_display_in() {
  local id
  id="$(macos_hardware_model_identifier 2>/dev/null || true)"
  case "$id" in
    MacBookAir10,1|Mac14,2) printf '13in' ;;
    *) return 1 ;;
  esac
}

# About This Mac marketing string from the login user's SystemProfiler plist.
macos_cpu_names_marketing() {
  local serial4="${1:-}"
  local plist="$HOME/Library/Preferences/com.apple.SystemProfiler.plist"
  [ -f "$plist" ] || return 1
  command_exists python3 || return 1
  python3 -c '
import plistlib, sys
path, serial4 = sys.argv[1], sys.argv[2]
try:
    with open(path, "rb") as f:
        data = plistlib.load(f)
except Exception:
    sys.exit(1)
names = data.get("CPU Names") or {}
if not isinstance(names, dict) or not names:
    sys.exit(1)

def usable(v):
    return isinstance(v, str) and v.strip()

serial_hits = []
en_hits = []
any_hits = []
for k, v in names.items():
    if not usable(v):
        continue
    any_hits.append(v.strip())
    key = str(k)
    if serial4 and key.startswith(serial4 + "-"):
        serial_hits.append(v.strip())
        if "-en-" in key:
            en_hits.append(v.strip())
if en_hits:
    print(en_hits[0])
elif serial_hits:
    print(serial_hits[0])
elif any_hits:
    print(any_hits[0])
else:
    sys.exit(1)
' "$plist" "$serial4"
}

macos_parse_screen_in() {
  local s="${1:-}"
  local piece
  piece="$(printf '%s' "$s" | grep -oE '[0-9]+(\.[0-9]+)?-[Ii]nch|[0-9]+(\.[0-9]+)? [Ii]nch' | head -1 || true)"
  [ -n "$piece" ] || return 1
  printf '%s' "$piece" | sed -E 's/[ -][Ii]nch$/in/'
}

macos_parse_model_year() {
  local s="${1:-}"
  local year
  year="$(printf '%s' "$s" | grep -oE '20[0-9]{2}' | tail -1 || true)"
  [ -n "$year" ] || return 1
  printf '%s' "$year"
}

macos_builtin_display_in() {
  command_exists system_profiler || return 1
  macos_parse_screen_in "$(system_profiler SPDisplaysDataType 2>/dev/null || true)"
}

# Apple's catalog name for this config code (serial last 4), e.g. MacBook Pro (16-inch, 2024).
macos_apple_support_marketing() {
  local cc="${1:-}"
  local xml name
  [ -n "$cc" ] || return 1
  command_exists curl || return 1
  xml="$(curl -fsSL --max-time 8 "https://support-sp.apple.com/sp/product?cc=${cc}" 2>/dev/null || true)"
  name="$(printf '%s' "$xml" | sed -n 's/.*<name>\([^<]*\)<\/name>.*/\1/p' | head -1)"
  name="$(printf '%s' "$name" | sed -E 's/^[[:space:]]+//;s/[[:space:]]+$//')"
  [ -n "$name" ] || return 1
  case "$name" in
    *[Ee]rror*|*[Uu]nknown*) return 1 ;;
  esac
  printf '%s' "$name"
}

macos_marketing_detail_string() {
  local serial4="${1:-}"
  local s=""
  s="$(macos_ioreg_product_name 2>/dev/null || true)"
  if [ -z "$s" ]; then
    s="$(macos_cpu_names_marketing "$serial4" 2>/dev/null || true)"
  fi
  if [ -z "$s" ]; then
    s="$(macos_apple_support_marketing "$serial4" || true)"
  fi
  printf '%s' "$s"
}

macos_generate_computer_name() {
  local login model marketing size year serial serial4 body
  login="$(macos_bootstrap_login_user)"
  [ -n "$login" ] || return 1

  serial="$(macos_hardware_serial)"
  serial4=""
  if [ -n "$serial" ] && [ "${#serial}" -ge 4 ]; then
    serial4="${serial: -4}"
  elif [ -n "$serial" ]; then
    serial4="$serial"
  fi

  model="$(macos_hardware_model_name 2>/dev/null || true)"
  marketing="$(macos_marketing_detail_string "$serial4")"
  size="$(macos_parse_screen_in "$marketing" 2>/dev/null || true)"
  if [ -z "$size" ]; then
    size="$(macos_early_m_air_display_in 2>/dev/null || true)"
  fi
  if [ -z "$size" ]; then
    size="$(macos_builtin_display_in 2>/dev/null || true)"
  fi
  year="$(macos_parse_model_year "$marketing" 2>/dev/null || true)"

  if [ -n "$model" ]; then
    body="$(macos_spaces_to_hyphens "$model")"
    [ -n "$size" ] && body="${body}-${size}"
    [ -n "$year" ] && body="${body}-${year}"
  elif [ -n "$marketing" ]; then
    body="$(macos_normalize_marketing "$marketing")"
  else
    log_warn "Could not read Mac marketing name; not generating ComputerName."
    return 1
  fi
  [ -n "$body" ] || return 1

  if [ -z "$serial4" ]; then
    log_warn "Could not read hardware serial; generated name will omit the suffix."
  fi
  case "$model" in
    *MacBook*|*iMac*)
      if [ -z "$size" ]; then
        log_warn "Could not determine screen size for ComputerName."
      fi
      ;;
  esac
  if [ -z "$year" ]; then
    log_warn "Could not determine model year for ComputerName."
  fi

  if [ -n "$serial4" ]; then
    printf '%s-%s-%s' "$login" "$body" "$serial4"
  else
    printf '%s-%s' "$login" "$body"
  fi
}

# Sets MACOS_RESOLVED_COMPUTER_NAME, MACOS_RESOLVED_HOST_NAME, MACOS_RESOLVED_LOCAL_HOST_NAME.
macos_bootstrap_resolve_machine_names() {
  local computer host local_name generated

  if [ -n "${MACOS_RESOLVED_NAMES_DONE:-}" ]; then
    return 0
  fi

  computer="${COMPUTER_NAME:-}"
  if [ -z "$computer" ]; then
    generated="$(macos_generate_computer_name || true)"
    computer="$generated"
  fi
  computer="$(macos_spaces_to_hyphens "$computer")"

  if [ -n "${HOST_NAME:-}" ]; then
    host="$(macos_spaces_to_hyphens "$HOST_NAME")"
  else
    host="$computer"
  fi

  if [ -n "${LOCAL_HOST_NAME:-}" ]; then
    local_name="$(macos_bonjour_slug "$LOCAL_HOST_NAME")"
  else
    local_name="$(macos_bonjour_slug "$computer")"
  fi

  MACOS_RESOLVED_COMPUTER_NAME="$computer"
  MACOS_RESOLVED_HOST_NAME="$host"
  MACOS_RESOLVED_LOCAL_HOST_NAME="$local_name"
  MACOS_RESOLVED_NAMES_DONE=1
}

# When invoked as `sudo ./bootstrap.sh`, keep privileges but use the caller's
# HOME/USER so git, pyenv, and dotfiles do not land in /var/root.
macos_bootstrap_adopt_sudo_identity() {
  local home

  if [ "$(id -u)" -ne 0 ]; then
    return 0
  fi

  if ! running_via_sudo; then
    die "Logged in as root with no SUDO_USER. Run: sudo -u YOUR_USER $0 (or sudo ./bootstrap.sh from your account)."
  fi

  home="$(eval "echo ~${SUDO_USER}")"
  if [ -z "$home" ] || [ ! -d "$home" ]; then
    die "Could not resolve home directory for ${SUDO_USER}"
  fi

  export USER="$SUDO_USER"
  export LOGNAME="$SUDO_USER"
  export HOME="$home"
  log_info "sudo as ${SUDO_USER} (HOME=$HOME)"
}

# Homebrew/pyenv refuse euid 0. Run those tools as the login user under sudo.
run_user() {
  if is_dry_run; then
    log_dim "[dry-run] $*"
    return 0
  fi
  if running_via_sudo; then
    sudo -u "$SUDO_USER" -H -- "$@"
  else
    "$@"
  fi
}

# brew as the login user, with progress on long fetches and installs.
run_brew() {
  run_user env PATH="$PATH" HOMEBREW_COLOR=1 HOMEBREW_VERBOSE=1 brew "$@"
}

# Ensure pyenv shims are on PATH for this process.
eval_pyenv() {
  export PYENV_ROOT="${PYENV_ROOT:-$HOME/.pyenv}"
  eval_brew_shellenv
  if command_exists pyenv; then
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
  fi
}

# Ensure Homebrew is on PATH for the rest of this process (Apple Silicon + Intel).
eval_brew_shellenv() {
  if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [ -x /usr/local/bin/brew ]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
}

ensure_dir() {
  run mkdir -p "$1"
}

# Symlink src -> dst. Existing real files are backed up; matching links are left alone.
link_file() {
  local src="$1"
  local dst="$2"
  local dst_dir current bak

  if [ ! -e "$src" ] && [ ! -L "$src" ]; then
    die "Cannot link missing source: $src"
  fi

  dst_dir="$(dirname "$dst")"
  ensure_dir "$dst_dir"

  if [ -L "$dst" ]; then
    current="$(readlink "$dst")"
    if [ "$current" = "$src" ]; then
      log_success "Already linked $(basename "$dst")"
      return 0
    fi
    log_warn "Replacing symlink $dst"
    run rm "$dst"
  elif [ -e "$dst" ]; then
    bak="${dst}.bak.$(date +%Y%m%d%H%M%S)"
    log_warn "Backing up existing $(basename "$dst") -> $bak"
    run mv "$dst" "$bak"
  fi

  run ln -s "$src" "$dst"
  log_success "Linked $dst"
}

# Keep sudo alive while a long module runs. Call macos_bootstrap_sudo_stop when done.
_SUDO_KEEPALIVE_PID=""

macos_bootstrap_sudo_start() {
  if is_dry_run; then
    return 0
  fi
  if [ "$(id -u)" -eq 0 ]; then
    return 0
  fi
  sudo -v
  (
    while true; do
      sudo -n true
      sleep 50
      kill -0 "$$" || exit
    done
  ) 2>/dev/null &
  _SUDO_KEEPALIVE_PID=$!
}

macos_bootstrap_sudo_stop() {
  if [ -n "${_SUDO_KEEPALIVE_PID:-}" ]; then
    kill "${_SUDO_KEEPALIVE_PID}" 2>/dev/null || true
    _SUDO_KEEPALIVE_PID=""
  fi
}

module_name_from_path() {
  local base
  base="$(basename "$1" .sh)"
  printf '%s' "$base" | sed 's/^[0-9][0-9]*-//'
}

list_module_files() {
  local f
  for f in "$MACOS_BOOTSTRAP_ROOT/modules/"*.sh; do
    [ -f "$f" ] || continue
    printf '%s\n' "$f"
  done | sort
}
